### ISSUE TITLE
Push new version to Hackage

### ISSUE THREAD

**Issue by treszkai** [Happstack/happstack-lite#1]
The latest version of happstack-lite requires happstack-server<7.6, but the one on Hackage still requires <7.5.

**Comment by tomjaguarpaw** [comment]
And please change to `< 7.7`!  I have done this locally and it seems to be fine.

**Comment by tomjaguarpaw** [comment]
@ddssff Thanks for merging the bump to `< 7.7`: https://github.com/Happstack/happstack-lite/pull/2

Could the package information on Hackage also be edited to incorporate this? https://hackage.haskell.org/package/happstack-lite

Thanks!

**Comment by ddssff** [comment]
Yes, that should happen soon.

**Comment by stepcut** [comment]
7.3.7 is now on hackage.

**Comment by tomjaguarpaw** [comment]
Thanks! And thanks for keeping this really handy package going.
